site_name: IIoT – Industrial Internet of Things
site_url: https://wildle.github.io/MCI-AUT-IIoT/
site_author: Lenard Wild

nav:
  - 'Organisatorisches':
    - 'Aufbau der Lehrveranstaltung': 1_Organisatorisches.md
    - 'Projekt': 1_Projekt.md
    - 'Leistungsbewertung': 1_Leistungsbewertung.md
  - 'Industrial Internet of Things':
    - 'Grundlagen': 6_IIoT_Grundlagen.md
    - 'MQTT': 6_MQTT.md
    - 'TwinCAT MQTT-Client': 6_TwinCAT_MQTT.md
    - 'REST': 6_REST.md
    - 'Datenspeicherung': 7_Datenspeicherung.md
  - 'Machine Learning':
    - 'Regressionsmodelle': 8_Regression.md
    - 'Lineare Regression mit Python und Scikit-Learn': 8_Regression_Python.ipynb
    - 'Klassifikationsmodelle': 9_Klassifizierung.md
    - 'Klassifikation und Feature Engineering mit Python und Scikit-Learn': 9_Classification_Python.ipynb

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - attr_list

plugins:
  - mkdocs-jupyter

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML

dev_addr: '127.0.0.1:7000'
